### PR TITLE
belindas-closet-nextjs_8_441_new-front-page-design

### PR DESCRIPTION
**Pull request by nickolasram**
This is a mock pull requests to discuss a new front page design I'm working on. So far, this is the design I like the best:

Heading in scroller

Here's some screenshots to show how it looks in a browser:

Screenshot 2024-07-08 3 54 26 PM
Screenshot 2024-07-08 3 54 43 PM
Screenshot 2024-07-08 3 54 54 PM
Screenshot 2024-07-08 3 55 03 PM

For now I just put the "menswear" and "womenswear" as some extra placeholder categories we can show on the page, but we can adjust what we show in that section of the page.
I also think we should include a section similar to this area they have on stitchfix's website:

Screenshot 2024-07-08 3 59 10 PM

suggestions?

### CODE REVIEW

**Comment by keiffer213** [comment]
Thanks for doing this! It looks great, we'll probably hold off on re-working the front page for now to finish up the app. But at least now we have this for when we do have the resources to rework the front page!

**Comment by bcko** [comment]
@nickolasram , Thank you for your work on this. Would you be interested in implementing it as well? If so, could you provide an estimate of how long it might take?

**Comment by nickolasram** [comment]
@bcko Yeah, I could implement it. I'll try to have it done on by the 1st

**Comment by bcko** [comment]
> @bcko Yeah, I could implement it. I'll try to have it done on by the 1st

Sounds good.

**Pull request closed without merging**
