### PR TITLE
 belindas-closet-nextjs_10_526_Add_charts

### PR DESCRIPTION
**Pull request by Alzavio**
Resolves 526

Progress Summary: Adds dummy charts in the style of the Figma design until we have data

Key Learnings: N/a, I'm used to Chart.js

### CODE REVIEW

**Comment by bcko** [comment]
@Alzavio Great job. can you resolve conflicts and post a screenrecording of the feature? Thanks

**Review by nwm516 — CHANGES_REQUESTED** [review]
I made some changes on my end in order for this to show: 


526 Add Charts PR Review

I ran `npm install chart.js react-chartjs-2
`, then `npm run build
npm run dev
` to get it started.

I created a "weeklyActivity" folder and placed it within the "dashboard" folder for the "weeklyActivity.tsx" file to live, which I did also rename to "page.tsx".

Based upon that, perhaps implementing those changes can help the errors?

**Review by Asfand00 — APPROVED** [review]
This is what I see on my end:
belindas_dashboard1
belindas_dashboard2

Looks good, seems like the changes @nwm516 suggested might have helped with the errors you were having. also, data is highlighted when I hover over the bar itself so good work on that. 

I am noticing minor bugs and funkiness with the chart such as this image below:
dashboard_bug1

there is also endless navigation with the arrows and the data isn't consistent but since this is just dummy data and getting a basic chart going its ok for now @Alzavio.   

sidenote: the bar graphs on the bottom for 30 days is thinner than the one shown in @nwm516 but it's a minor change if we need to change the size of them. 

Looks like you still need to resolve the branch conflicts still, but ill approve for now because the chart is showing up for me.

**Review by Asfand00 — CHANGES_REQUESTED** [review]
This is what I see on my end as per the update @nwm516, I ran `npm ci` as you did yourself. 
belindas-dashboard-chart
The sidebar menu does cover part of the charts, but I suppose that can be fixed later, since this is just implementing the chart with dummy data, its fine how it looks for now.

I also did notice these console errors when running `npm test` 
belindas-console-errors-dashboard
belindas-console-errors-dashboard2

the console errors are fine for now at this stage, but they should be corrected at some point, I think. 

Other than that, the only small thing I would request is the removal of carets in the package.json file (should've mentioned it before in earlier post) and this PR should be good for approval. Thanks for the work! @nwm516. 
belindas-package-json-chartjs

**Review by gitbiruk2010 — APPROVED** [review]
Findings:
run 'npm test' and gives the same console error as asfand00 mentioned.
sidebar menu remains the same

running 'npm ci': since it is performing a clean install, which is strictly as listed in package-lock.json, of course it messes with the new sample data and existing page in app/dashboard/ & app/dashboard/weeklyActivity/ page.
**Otherwise, the rest looks good on my end.**

https://github.com/user-attachments/assets/97541b6a-71ff-423b-9502-089e4b3b4dd2

I think we will get to the rest of the fixes once we have a real data.

**Pull request merged**
