### PR TITLE
This is the Unit Test for Dashboard

### PR DESCRIPTION
**Pull request by kaimanasse15**
This is the Unit Test for Dashboard
Issue: #367

### CODE REVIEW

**Review by alasali1 — APPROVED** [review]
The code makes sense to me and I also got a passing result when running jest.
image

**Review by el-riber — APPROVED** [review]
it looks great!

**Comment by miqo1385** [comment]
It seems like all the tests passed.

**Review by taylorpapke — APPROVED** [review]
Works for me:
Screenshot 2024-05-18 at 12 54 33 PM

**Pull request merged**
