### PR TITLE
belindas-closet-nextjs_2_208_add-product-card-component

### LINKED ISSUE #207: USER STORIES: Product Card (Product Display Enhancement)
As a developer, I want to create a product card component to enhance product display.
Task:
- [x] #208

### LINKED ISSUE #208: Product Card: Create a product card component.
Resolves #207

### PR DESCRIPTION
**Pull request by TroyFPV48**
resolves #207   

Currently, Products are using static image, we need to find a method to store and display individual product image.
image

### CODE REVIEW

**Comment by tinpham5614** [comment]
@TroyFPV48 Please check and fix the error for this PR. Seems like an error due to the update from next 13 to next 14.
image

**Comment by TroyFPV48** [comment]
> @TroyFPV48 Please check and fix the error for this PR. Seems like an error due to the update from next 13 to next 14. image

Hi Tin, sorry for changing Nextjs version, I downgraded it back to 13.4.9 and it worked.

**Review by taylorpapke — APPROVED** [review]
Works on my end. I am seeing the cards with a description:
Screenshot 2024-02-18 at 11 33 56 AM

**Review by tinpham5614 — APPROVED** [review]
LGTM. Eventually, we will need to start using MUI, which can be done in another issue.

**Pull request merged**
