### PR TITLE
belindas-closet-nextjs_5_293_edit-user-role-button-and-page-styling

### PR DESCRIPTION
**Pull request by nwm516**
Resolves <issue #293 >

- Link "Edit User Role" button to correct page
- Style elements to match Creator page
- Fix spelling errors

https://github.com/SeattleColleges/belindas-closet-nextjs/assets/36825393/05e58aa4-06c8-424f-8afe-be133fa77157

### CODE REVIEW

**Comment by nickolasram** [comment]
Just checked it out. Everything seems to be working as it should be and meeting the criteria as outlined by the miro board and issue #293 👌

**Review by nickolasram — APPROVED** [review]
Just checked it out. Everything seems to be working as it should be and is meeting the criteria as outlined by the miro board and issue #293 👌

**Review by cshimm — APPROVED** [review]
Everything works as expected. Looks good to me.

**Review by IsaacJrTypes — COMMENTED** [review]
I was wondering, why did you decide not to use material ui components? Great job overall

**Review by taylorpapke — APPROVED** [review]
Awesome! Admin page edit user roles button is routing properly and the creator page is looking good:
Screenshot 2024-04-22 at 2 44 42 PM

**Comment by BradleyCharles** [comment]
Looking good!

creator-page

**Pull request merged**
