### PR TITLE
belindas_closet_7_383_qrcode_implementation

### LINKED ISSUE #382: USER STORY: Implement QR Code
As a dev, I want to implement the QR code technology. I would like to create a google form as the endpoint for the QR code. This data should be available to devs during development.

- [x] #383
- [ ] Implement Google form

QR code implementation

### LINKED ISSUE #383: Implement QR code: component
resolves #382 

- [x] Implement QR code
- [ ] Connect google page to endpoint
- [ ] (optional) Add NSC image to center of QR Code

Current Progress
image

Links to a dummy website

updated guide on implementation
https://www.notion.so/QR-Code-Implementation-51791fb0d4284b1681ebe17f332fdf39

### PR DESCRIPTION
**Pull request by JesseCaddell**
Resolves #383 which will resolve #382 (sorry)

This PR implements the QR Code technology within the back-end and also front-end.

npm run dev to get started

npm install to install dependencies 

navigate to http://localhost:8080/qrcode-page

Use your phone on the QR code to test its endpoint.

You can modify the endpoint within app/qrcode-page/page.tsx and test again if you wish
image

TODO:
Create google form, replace endpoint with new google form
_Enable auto-merge (squash) at the bottom of the page._

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Did an `npm install` first to get the required modules. Looks like everything is working fine and I was redirected to the northseattle.edu website:
Screenshot 2024-05-28 at 9 18 57 PM
IMG_B39818181F49-1

**Review by Robel-003 — APPROVED** [review]
QR code working for me after installing necessary dependencies. Really cool feature!

IMG_7030

**Comment by MuhammadNSC** [comment]
The QRCodeGenerator component is a well-implemented addition for our project. It provides a flexible and easy-to-use solution for generating QR code using your mobile phone. Initially i was having trouble opening the QR code page but after doing ```npm istall``` I was able to connect to the page and used my mobile phone to access the QR code.
IMG_7764

**Review by heosman — APPROVED** [review]
Scanning the barcade with my phone camera opened the Google Contact Information form.

image
image

**Review by BradleyCharles — COMMENTED** [review]
Looks good with the new light and dark mode changes too!

Screenshot 2024-05-30 201019
Screenshot 2024-05-30 201124

**Pull request merged**
