### PR TITLE
belindas-closet-nextjs_5_315_Dashboard Page

### LINKED ISSUE #315: Link should only be available to admins that are signed in.
related to issue #283 
Link should only be available to admins that are signed in.
belindaadmindashboard

### PR DESCRIPTION
**Pull request by BradleyCharles**
Resolves #315 
Checks if the user is logged in as admin and displays the link to the dashboard if they are.

Signed in as user:
dashboard-user

Signed in as admin:
dashboard-admin

### CODE REVIEW

**Comment by Seiyaroo** [comment]
It's probable I am not on a designated admin account but @BradleyCharles I am not seeing Dashboard when using Admin2's login information. Would you mind DMing me the same login info on slack so I can test this? I don't doubt your work, just want to do my due diligence :)

**Review by bennettsf — APPROVED** [review]
Working as intended on my end, including the dashboard button being removed on sign-out from an admin account! 

https://github.com/SeattleColleges/belindas-closet-nextjs/assets/33855430/fa15db15-186e-4196-baf3-ab6880327be4

**Comment by tinpham5614** [comment]
I suggest using Prettier, a VS Code extension that ensures code format consistency.

**Review by intisarosman1 — APPROVED** [review]
The Dashboard link in the nav bar does not appear while logged out, but when I log in as an admin user I can access it.

**Comment by BradleyCharles** [comment]
@Seiyaroo When I test I am using my own MongoDB created users. I am unsure what admin2 user is that you are referring to and I also see that @bennettsf is also using it in their video which does seem to be working.

**Comment by BradleyCharles** [comment]
@tinpham5614 I am using prettier. Which lines specifically look inconsistent? I would like my code to be easy to read

**Review by Seiyaroo — APPROVED** [review]
@BradleyCharles yeah I see in the video above, its working correctly. So i'll forego my previous comment haha. Just gonna give my approval as it seems to work fine :)

**Comment by tinpham5614** [comment]
> @tinpham5614 I am using prettier. Which lines specifically look inconsistent? I would like my code to be easy to read

As for the screenshot, the content won't change but the format. 
Prettier formats the red part.
These unnecessary changes can cause conflicts that we try to avoid.

image

**Comment by BradleyCharles** [comment]
@tinpham5614 
Thank you, for pointing this out to me since I was curious about this. 
The red was actually a change that my prettier extension caused when I added the dashboard link to the navbar in part 1 of my user story. After changing some settings in the extension it is actually undoing the formatting to revert it back to the original formatting in the green. 

is there a specific configuration that I can use for my prettier settings so that I can stay consistent with what everyone else is using? The default settings is what caused the unnecessary change in the first place.

**Comment by tinpham5614** [comment]
I have the Prettier default setting.
I usually do format as the short video below

[Screencast from 2024-04-27 14-53-48.webm](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/72054441/cb4ef367-43b3-4d76-a91d-1bf126795001)

**Pull request merged**
