### PR TITLE
 updated-package-lock.json _spring13 _ #548  _ Updated emailjs-com dependency

### PR DESCRIPTION
**Pull request by miqo1385**
This is a pull request!

Please use the following format for the title:
 updated-package-lock.json _spring13 _ #548  _ Updated emailjs-com dependency

Please fill out this description with the following:
Resolves issue #548 
This pull request update the dependency emailjs-com for the new one called emailjs-com/browser

Screenshot 2024-10-27 at 10 55 27 PM

### CODE REVIEW

**Review by Asfand00 — CHANGES_REQUESTED** [review]
Looks good to me, ran `npm test` and` npm run dev` and both were successful. No general issues were found. The only minor thing that needs change is the removal of the carets, once you do that @miqo1385 the PR will get approved, thanks. 
belinda-closet-dependencies-emailjs

**Comment by Diego-Cano** [comment]
All tests ran smoothly for this pull request—11 suites and 26 tests all passed without any problems. I noticed a few minor things: there are repeated warnings about the punycode module being deprecated, so maybe something to look at in future updates. Also, I saw some console logs from page.tsx and ProductCard.tsx showing up in the test output, which might be worth cleaning up just to keep things tidy.

There was also a jsdom warning about navigation not being implemented. It doesn’t seem to impact the functionality now, but it could be something to consider if we get into more complex routing tests down the line. Here’s a quick read on testing with [Jest](https://jestjs.io/docs/configuration).

Screenshot 2024-11-03 at 9 58 40 AM

Screenshot 2024-11-03 at 10 03 59 AM

**Review by Diego-Cano — APPROVED** [review]
Great job!

**Review by Asfand00 — APPROVED** [review]
Thanks @miqo1385, everything looks good. Ran the tests and it came out fine. 
belindas-package-json-update

**Review by el-riber — APPROVED** [review]

**Comment by Bejarano03** [comment]
LGTM. The application runs with no errors and it also passes all the tests.

Screenshot 2024-11-06 at 11 05 32 PM

**Pull request merged**
