### PR TITLE
Contact page and Admin page unit test

### PR DESCRIPTION
**Pull request by kaimanasse15**
Issue: #368

### CODE REVIEW

**Comment by Diego-Cano** [comment]
I tried to un the tests and ran into a few errors. 
Screenshot 2024-05-16 at 6 14 10 PM

**Review by el-riber — COMMENTED** [review]
Your test code looks mostly correct, but there are a couple of things to check:

Ensure that the DonationInfo component contains the elements you are testing for, such as a heading with the text "Donation Info".
Ensure the alias @ is properly configured in your project so that the import statement import DonationInfo from '@/app/donation-info/page'; resolves correctly.
Screenshot 2024-05-16 at 8 49 44 PM

**Comment by taylorpapke** [comment]
@kaimanasse15 Can I close this PR? I think it's too conflicted to merge.

**Comment by kaimanasse15** [comment]
Yeah sure!. Thanks @taylorpapke

**Pull request closed without merging**
