### PR TITLE
belindas-closet-nextjs_5_334_add-a-link-button-to-visualization-dashboard

### LINKED ISSUE #334: USER STORY: Add a link button to visualization dashboard
Add the link to the admin page that lead to dashboard page

### PR DESCRIPTION
**Pull request by kaimanasse15**
The link has been added in the dashboard button in the admin page
Resolve #334

### CODE REVIEW

**Review by tinpham5614 — APPROVED** [review]
You can use the Material UI button and Link components to implement this.
Looks good!

**Comment by kaimanasse15** [comment]
@tinpham5614 Hi Tin, you mean the style look like this right?
image

**Comment by tinpham5614** [comment]
@kaimanasse15,
Not sure how it was implemented.
You can check this out if you are not familiar https://mui.com/material-ui/react-button/

**Review by taylorpapke — APPROVED** [review]
Looks good to me:
Screenshot 2024-05-01 at 1 29 35 AM

**Review by keiffer213 — APPROVED** [review]
Looks great to me! Dashboard button shows up on the admin-page, and when clicked it routes over to the dashboard page. 

The button is the same as the other buttons, so it all looks cohesive!

image

**Comment by nickolasram** [comment]
@kaimanasse15 Looks good, but it can't be automatically merged because your commits aren't signed. [Here is a tutorial on how to sign your commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for the next sprint.

**Comment by MuhammadNSC** [comment]
Works as explained in the Issue. Maybe you can import the material UI in the Admin page and wrap the button in the material UI theme. Similar to what I did in the creator page
Screenshot 2024-05-01 at 6 18 15 PM

**Review by kaimanasse15 — COMMENTED** [review]
It worked when I added the UI style

**Comment by kaimanasse15** [comment]
image

**Review by intisarosman1 — APPROVED** [review]
The dashboard button on the admin page directs me to the dashboard page.
Screenshot 2024-05-01 225135

**Pull request merged**
