### PR TITLE
Belindas-closet-nextjs-1-153-update-react-query-package

### PR DESCRIPTION
**Pull request by Ali-7s**
Installed @tanstack/react-query which is the up to date version of react-query
image
https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-4

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
LGTM

**Comment by brinkbrink** [comment]
While we don't always need to (or want to) use the latest versions of packages I do think this one could be beneficial for us. But I do want to make sure this is something @tinpham5614 @Robel-003 or @bcko are aware of. We should also make sure we communicate this change to the team. [This doc](https://tanstack.com/query/latest/docs/react/overview) explains the benefits well. Sorry if y'all have already discussed this.

**Comment by taylorpapke** [comment]
In regards to the conflicts @Ali-7s, @Exochos just fixed the same conflicts for the nsc-events-nextjs version of this PR and could potentially provide insight if needed.

**Review by tinpham5614 — CHANGES_REQUESTED** [review]
A conflict needs to be fixed.

**Comment by Exochos** [comment]
Fixed merge conflict.

**Review by tinpham5614 — APPROVED** [review]
LGTM, thank you for fixing the conflict.

**Pull request merged**
