### PR TITLE
belinda-nextjs-410-add-belinda-designs

### LINKED ISSUE #410: Chore: Add-belinda-designs
I would like to add Belinda's designs.

Demo:
image_720
image_720

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #410 

This PR will add Belinda's design images

### Demo:
**Light mode**
image

**Dark mode**
image

### CODE REVIEW

**Comment by Alzavio** [comment]
Is it possible to use .svg's then adjust the color based on dark vs light mode, just so we don't have the odd white png border and a better contrast with the images?

**Comment by kaimanasse15** [comment]
image
image
Hi Tin,
It works for me. Looks great

**Review by larsswenson — APPROVED** [review]
This looks great, Tin! The light/dark mode feature is really effective. The only suggestion I'd make, which I think has been mentioned here is the image contrast in dark mode, but I also think it's an aesthetic preference rather than an accessibility issue. One can easily read the text of the categories.

**Review by Alzavio — APPROVED** [review]

**Comment by tinpham5614** [comment]
> Is it possible to use .svg's then adjust the color based on dark vs light mode, just so we don't have the odd white png border and a better contrast with the images?

It is possible to use .svg in Next.js. How can we convert from PNG to SVG? I look forward to your perspective.

**Comment by Alzavio** [comment]
> > Is it possible to use .svg's then adjust the color based on dark vs light mode, just so we don't have the odd white png border and a better contrast with the images?
> 
> It is possible to use .svg in Next.js. How can we convert from PNG to SVG? I look forward to your perspective.

I don't know where the current icons were found, but if they come from an icon pack, they should have the .svg versions available.

If not, Inkscape can convert png's to svg's, but how good it is at doing that depends on the quality of the image.

**Comment by tinpham5614** [comment]
@Alzavio I tagged you in the Slack channel where we store images/icons.
I tried to convert using [Adobe](https://www.adobe.com/express/feature/image/convert/png-to-svg), but the result isn't expected.

**Comment by MuhammadNSC** [comment]
This works really well! Having to navigate between dark  and light mode is a great feature to add. I also like the new icons implemented for the items. 

https://github.com/SeattleColleges/belindas-closet-nextjs/assets/117953848/8fcf2227-0016-4f05-ba69-f2e955743502

**Review by heosman — APPROVED** [review]
The new logo and the icons for the product categories look great. 

If you're still working out on how to fix the white outlines from the pngs of the category icons, I'll throw in a suggestion. An alternative idea could be to have inverted versions of the icons and when dark mode is on, you would use the inverted images, if that's possible. Here is what it would look like for comparison:

image

**Comment by tinpham5614** [comment]
@heosman 
Did you implement it on your side?
How did you inverted images as you suggested? 
Any resources are appreciated.

**Comment by heosman** [comment]
> @heosman Did you implement it on your side? How did you inverted images as you suggested? Any resources are appreciated.

@tinpham5614 I just replaced one of the images to see how it would look. I used a photo-editing software (paint.net) to invert the colors, you could probably use Photoshop too.

**Comment by tinpham5614** [comment]
@heosman 
Thank you for the information. I have implemented this on the other PR. 
Also, I used Inkscape to invert color images.

**Pull request merged**
