### PR TITLE
belindas-closet-nextjs-10-486-new-home-page

### PR DESCRIPTION
**Pull request by nickolasram**
resolves #486

Restyled the home page as well as the navbar and created a new footer. All the categories on the home page are pretty easy to change and we can remove or add some easily as well.

https://github.com/user-attachments/assets/9c100ded-16cd-4185-96fa-81216523d2ff

I used stock photos from istock just to get a sense of what the color filters will look like in practice. EXCEPT for the images in the banner. Those are pictures I pulled from a facebook post about Belinda's Closet and the Belinda's closet page on the NSC website.

Some pages will look funny with the footer being too high up because there's no content there yet to push it down.

When you test this locally, the Category Blocks on the front page should look differently than in the video. They should look like this: 

Screenshot 2024-08-01 212233

But again, those are just stock photos anyway. 

I made the image stop scrolling on hover as it could potentially be a useful if we want to add more functionality to it. But it can easily be changed too if it's too jarring. Just gotta delete these lines:

Screenshot 2024-08-01 213217

I decided to make the "view all categories link" just open a popup for now. Also, some elements don't have fully responsive designs yet.

### CODE REVIEW

**Review by Asfand00 — APPROVED** [review]
Impressive work @nickolasram, I'm seeing the same things as your video and image in these screenshots:
belinda-closet-new-home-page1
belinda-closet-new-home-page2
belinda-closet-new-home-page3
belinda-closet-new-home-page4
belinda-closet-new-home-page5

I see what you mean about the footer in screenshot number 4, not sure if there is a concrete way to make the footer appear always at the bottom of the page, but I suppose adding content like you said will justify it. 

The pop up on screenshot 5 is fine as is and the hover thing is ok for me but not sure about others, will have to wait and see on that one if we need to remove it. I also like the scrolling feature for the items and for recent items. Overall, it's a really nice look, good job.

**Review by alasali1 — COMMENTED** [review]
I like the new elements and features added to the redesigned homepage. I especially like the image banner at the top, and the three carousels displaying recently added products. I am having some issues with my backend at the moment, so I am not sure if the recently added products sections are displaying the newest products and/or replacing older displayed products at this time.

**Comment by Alzavio** [comment]
Looks great, I like that the images at the top scroll right by themselves. But maybe the white border between those should be different when dark theme is on? Not that important, just a thought

Screenshot 2024-08-06 at 21-01-16 Belinda's Closet
image

**Review by ken-ni — APPROVED** [review]
This looks really good! The carousel at the top is awesome and the page looks clean.
Screenshot from 2024-08-07 17-08-58
Screenshot from 2024-08-07 17-09-22
image
I tested all the buttons, they worked well. One really small nitpicky thing I noticed is the arrows to scroll left/right on the clothing categories seems a bit too close to the clothing buttons. It might look better if these arrows were a little further from the buttons but that's just my opinion.

**Pull request merged**
