### PR TITLE
Belinda_Nextjs_424_Contact_Us_Page_Sprint8

### PR DESCRIPTION
**Pull request by MuhammadNSC**
I added the contact us information here. I used the school number for phone# but i'm not sure which email to use.
Screenshot 2024-06-05 at 1 45 44 PM

### CODE REVIEW

**Comment by keiffer213** [comment]
This looks great! For the details such as the email and phone, you can just leave it blank for now, and this is probably good for review!

**Comment by Diego-Cano** [comment]
Hey team,

I took a look at the "Contact Us" page changes. It looks great! I appreciate the clarity and user-friendliness of the design. I noticed the placeholder for the email, and I think it's fine to leave it blank until we have the correct one. Using the school number for now would work too. One suggestion would be to add a "required" attribute to the email and message fields to make sure users don't submit incomplete forms.Also, we could add some error handling for invalid inputs (at some point), which would enhance the overall user experience.

Also, I found a helpful guide on UX Design for Forms:
https://designlab.com/blog/form-ui-design-best-practices

Thanks!

**Review by taylorpapke — APPROVED** [review]
Looks great!
Screenshot 2024-06-07 at 1 23 57 PM

**Review by keiffer213 — APPROVED** [review]

**Comment by ParysUnangst** [comment]
Great job Muhammad. This is well organized and easily read. I also appreciate the message box so the user is able to write what they need to help shorten the communication back and fourth!

**Pull request merged**
