### PR TITLE
belindas-closet-nextjs_8_remove-unrelated-fields_product-detail-page

### LINKED ISSUE #462: Remove unrelated fields being displayed on the Product-Detail-Page

### PR DESCRIPTION
**Pull request by Asfand00**
Resolves #462, #464 
Related #454 

note: this is from sprint 7 but I'm doing this for sprint 8 (that's why two labels are on this)

This PR is for updating the product detail page by displaying correct fields for certain products, removing unrelated ones from displaying.

Pants waist and inseam only appear on pants products:
pants

Shoes only display shoe size:
shoes

Shirts and other products display size and description
shirts
accessories

This is all I could find for incorrect fields
Let me know if this is correct or if changes are needed, I can make them

future suggestion issue: maybe adding more distinct fields for certain items

Update: Shoes only display shoe size, removed size field (Ignore previous image of shoes)
shoes2

### CODE REVIEW

**Comment by heosman** [comment]
I removed the Product Size field for Shoe products.

image

**Review by Asfand00 — COMMENTED** [review]
oh thanks @heosman, ill make these changes

**Comment by heosman** [comment]
> oh thanks @heosman, ill make these changes

@Asfand00 No worries, I already pushed the changes.

**Review by heosman — APPROVED** [review]

**Review by intisarosman1 — APPROVED** [review]
Looking good! Only the related fields show up. 

I did notice that your branch is outdated and doesn't reflect changes recently merged into main.
Screenshot 2024-07-03 205956
Screenshot 2024-07-03 210212

**Pull request merged**
