### PR TITLE
Belinda_NextJS_Sprint6_Added_Pronoun_Textfield

### PR DESCRIPTION
**Pull request by MuhammadNSC**
This is related to user story #375 I added the pronoun text field.
Before:
Screenshot 2024-05-15 at 3 53 07 PM
After:
Screenshot 2024-05-15 at 3 57 32 PM

### CODE REVIEW

**Review by BradleyCharles — APPROVED** [review]
Does what it says on the tin!

image

**Comment by tinpham5614** [comment]
I believe that upgrading the Next.js version is leading to the CI error.

**Comment by MuhammadNSC** [comment]
> I believe that upgrading the Next.js version is leading to the CI error.

@tinpham5614 I think so alswell. I tried downgrading my Next.js version but was having trouble.

Screenshot 2024-05-16 at 4 50 41 PM

**Comment by tinpham5614** [comment]
@MuhammadNSC Can you try to use node version 18.x instead of 19.x?

**Comment by MuhammadNSC** [comment]
@tinpham5614 I did npm install 18 but its still at v19

**Comment by miqo1385** [comment]
By the picture, I can't tell if that option is a dropdown with the pronunciations to be chosen, but if not, that could be a good incorporation.

**Comment by tinpham5614** [comment]
@MuhammadNSC  Can you try to install nvm and node as the instruction below?

**installs nvm (Node Version Manager)**
`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash`

**download and install Node.js**
`nvm install 20`

**verifies the right Node.js version is in the environment**
`node -v` 
should print `v20.13.1`

**verifies the right NPM version is in the environment**
`npm -v` 
should print `10.5.2`

Let me know if you need a meeting to troubleshoot this.

**Review by intisarosman1 — APPROVED** [review]
Great work! The pronoun field is there.
Screenshot 2024-05-20 234819

**Review by heosman — APPROVED** [review]
The pronouns field is added to the frontend and I was able to sign up successfully. However, because the pronouns field hasn't been added to backend and schema, the pronouns was not added to the user in the database.

**Comment by nickolasram** [comment]
Seems to be working fine, but can you try specifying in packages.json that you want to use a version prior to version 19?

**Review by taylorpapke — DISMISSED** [review]
Will approve and merge once this PR is passing CI.

**Comment by MuhammadNSC** [comment]
I have updated my node version and pushed the PR again

**Comment by Seiyaroo** [comment]
image

I am seeing a webpack error? Looks like it could be related to an NPM installation not being correct here. Not quite sure of the immediate problem child so to speak.

**Comment by tinpham5614** [comment]
This pull request is ready for review/approval. Additionally, we must refactor the backend for the app to function properly.

**Pull request merged**
