### PR TITLE
Chore belindas nextjs update api evironment

### PR DESCRIPTION
**Pull request by IsaacJrTypes**
This PR contains a quality of life update! Now you can set the API address from your .env file. If the developer is using a localhost based API address, the API address will be printed to the console.

How to test:
- Use the .env.sample to help set up your .env file. Once set, use `npm run dev` and run backend
- Make sure localhost port number matches with backend port number

### CODE REVIEW

**Review by bcko — APPROVED** [review]
Great job. We would need to document this as well.

**Review by Alzavio — APPROVED** [review]

**Comment by Alzavio** [comment]
Changing the api address via the env seems to be working

image

**Comment by intisarosman1** [comment]
How would I test this PR locally? Changing the API address in the env works fine, but I notice that there's issues with signing in and data not being fetched. Usually, I would comment out the env API URL lines on the Sign In page and next.config.js, but how would I do that in this PR?

**Comment by IsaacJrTypes** [comment]
@intisarosman1 I think the issue might the localhost address does not contain the same port value as the backend server. 
So If the frontend .env file contains 3005 (`API_URL=http://localhost:3005/api`) then the [backend listening port value should be 3005 ](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/main.ts#L25)

**Review by intisarosman1 — APPROVED** [review]
Thank you @IsaacJrTypes, I was able to get it working!
Screenshot 2024-07-31 204244

**Review by keiffer213 — APPROVED** [review]
Works for me as well! Thanks for this!

**Pull request merged**
