### PR TITLE
reactive menu fields (#287) (#292) belindas-closet-nextjs_5_reactive-menu-fields_287-292

### PR DESCRIPTION
**Pull request by Asfand00**
Resolves Issue #287 #292 
This pull request is for comparing with main because my branch 286-User-Story-Edit-Role had recent pushes (yellow warning)

I had recently updated my branch with main because it was a commit behind and did so but then the yellow message box appeared saying I had recent pushes, and I created another PR based on that.

### CODE REVIEW

**Comment by Asfand00** [comment]
I'm confused on this, should I close this pull request?

**Comment by nickolasram** [comment]
Hello, @Asfand00 when you say you had a yellow message box, do you mean one of the yellow message boxes that appear in this area here?
Screenshot 2024-04-20 235755

**Comment by Asfand00** [comment]
Yeah where it says 'this branch had recent pushes ago or something'

**Comment by Asfand00** [comment]
> Hello, @Asfand00 when you say you had a yellow message box, do you mean one of the yellow message boxes that appear in this area here?
> Screenshot 2024-04-20 235755
> 
> 

Yeah where it says this 'branch had recent pushes ago or something' with the compare and pull request button next to it. It showed up after I updated my branch with the current main

**Comment by nickolasram** [comment]
Yeah, unless you specifically made those commits and pushes, you can ignore that. You can delete this pull request 👍

**Comment by Asfand00** [comment]
> Yeah, unless you specifically made those commits and pushes, you can ignore that. You can close this pull request 👍

Oh ok. Thanks Nick. Yeah I didn't make any changes, commits, or pushes to my branch so I was confused.

**Pull request closed without merging**
