### PR TITLE
belinda-nextjs-05-282-image-upload-feedback

### LINKED ISSUE #282: Add Product Page: Image Upload Feedback
related to #280 
Image thumbnail should be visible upon uploading an image when adding product.

### PR DESCRIPTION
**Pull request by nickolasram**
resolves #282 

When you upload an image to the add product form, it should now show a preview of the image you are uploading. Here are some examples.
Screenshot 2024-04-18 200051
Screenshot 2024-04-18 200035
Screenshot 2024-04-18 200125

### CODE REVIEW

**Review by Ali-7s — APPROVED** [review]
LGTM.
Preview worked for me when uploading an image
image

**Comment by bennettsf** [comment]
Works great! I don't notice any issues and the preview seems to resize the image well depending on the image size you upload (big or small).

**Comment by cshimm** [comment]
Worked as expected for me. The image appeared in the right spot as soon as I clicked upload.
image

**Review by cshimm — APPROVED** [review]

**Comment by BradleyCharles** [comment]
Worked for me as well.
test

**Review by BradleyCharles — APPROVED** [review]

**Review by IsaacJrTypes — APPROVED** [review]
Great job! It looks awesome. I liked how you scaled the image!

**Pull request merged**
