### PR TITLE
belinda-nextjs_8_ 434_ archived-products-page

### PR DESCRIPTION
**Pull request by el-riber**
Please fill out this description with the following:
Resolves <issue #> 434

As a developer I created the page to archive products.
I made all the codes necessary to run the program. This includes the page, the api to make the connection between the images and the page.

Screenshot 2024-06-06 at 2 43 12 PM

### CODE REVIEW

**Review by taylorpapke — CHANGES_REQUESTED** [review]
This page should be converted to typescript like our other pages.

**Comment by MaddasaHatter** [comment]
Not seeing any updates to the code just yet to comply with code uniformity we'll need this updated before we can merge it.

**Comment by el-riber** [comment]
I am fixing and i will send soon

**Comment by taylorpapke** [comment]
Closing this PR since there is a newer version.

**Pull request closed without merging**
