### PR TITLE
belinda-nextjs-01-135-add-all-remaining-field

### LINKED ISSUE #135: Add Product Page: Add all remaining fields to page
As a developer, I want to add all remaining fields to the add product page:
- productType
- productGender
- productSizeShoe
- productSizes
- productSizePantsWaist
- productSizePantsInseam
- productDescription
- productImage

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #135

1. I want to add all remaining fields to the add product page:
- productType
- productGender
- productSizeShoe
- productSizes
- productSizePantsWaist
- productSizePantsInseam
- productDescription
- productImage

2. I also rename the file from **product-page** to **add-product-page**

DEMO:
image

### CODE REVIEW

**Review by Robel-003 — DISMISSED** [review]
This looks good. The dropdown options are simple and easy to use and the product image insertion works well! 
I did notice that when I click the “add product” in the nav bar, it takes me to a 404 page, but when I change the path in the url from (http://localhost:8080/product-page) to (http://localhost:8080/add-product-page) it takes me to the right page. Looks great overall!

**Review by taylorpapke — DISMISSED** [review]
Everything works as expected but definitely update this pull request to use the route [add-product-page](http://localhost:8080/add-product-page) as @Robel-003 mentioned as well.

**Comment by tinpham5614** [comment]
@Robel-003 @taylorpapke thank you for the feedback, I updated with the correct path to add-product-page.

**Review by taylorpapke — APPROVED** [review]

**Review by brinkbrink — APPROVED** [review]
Works as expected. Thanks for making requested change.

**Pull request merged**
