### PR TITLE
belindas-closet-nextjs_5_300_qa-testing-1

### PR DESCRIPTION
**Pull request by IsaacJrTypes**
Resolves <issue #300>
Description:
After researching, I found the right setup to run tests using jest. What was happening was jest could not understand typescript which would throw an error. Originally, I used a custom babel and jest setup to be able to run tests. I built the tests but kept seeing that using the custom babel would cause next.js to not use [SWC](https://swc.rs/). I downloaded the correct dependencies to be able to run jest with SWJ to maintain performance like next.js 13 intended :) 

Testing is limited given the inability to mock next.js router. I found some code that I included in this pull. [Here I found more discussions](https://github.com/vercel/next.js/discussions/23034) on mocking router.

The commit history shows my attempt at writing a test for the dropdown menu component. I could not finish it since the way the component is built, the routing string is pushed to the router.  You can see why mocking router is integral for further robust component testing. 

BC mentioned creating snapshot tests. After researching, I found that the material UI component generates CSS with numbers generated at the end of the class at runtime. So, a snapshot test will always yield a change that would give us false warnings. There are [methods of creating a wrapper that removes the numbers](https://medium.com/building-the-open-data-stack/resilient-snapshot-testing-with-material-ui-and-react-testing-library-befa04d4446f), but these solutions were made using a [now-deprecated API](https://mui.com/system/styles/api/#stylesprovider). We could still do snapshot testing, but we need to figure out which API to call to modify and apply the custom wrapper for testing.   

Those working on NSC events testing, try to replicate my settings. I am pretty sure it will work, but keep me updated if they don't work :)

Test Coverage Before:
CleanShot 2024-04-20 at 14 45 49@2x

Test Coverage After:
CleanShot 2024-04-20 at 15 05 36@2x

### CODE REVIEW

**Comment by IsaacJrTypes** [comment]
Adding write up from draft pull request on 4/18

After researching, I was able to find the configurations to get jest to run with typescript without encountering errors. Previously, I could not write tests on components because jest would complain about TSX files and throw runtime errors. Many tutorials later, I found the right environment for creating tests. An issue I am running into is I cannot run jest tests on certain components (non page components) without mocking the useRouter. I plan on finishing up writing the page tests since they are pretty straightforward.
Here is more informations on how other's were able to mock useRouter for jest. If you can figure out the right implementation, please let me know!
https://github.com/vercel/next.js/discussions/23034

**Review by taylorpapke — APPROVED** [review]
I pulled this branch, did an `npm install` and was able to `npm run test:coverage` for the following results:
Screenshot 2024-04-23 at 2 00 06 AM

What should we make of the socket security failure? @brinkbrink @Seiyaroo

**Review by heosman — APPROVED** [review]
LGTM, all of the tests passed for me.

image

**Comment by MuhammadNSC** [comment]
Ran the test and all tests passed on my end

Screenshot 2024-04-24 at 4 02 58 PM

**Comment by Diego-Cano** [comment]
The tests look all good to me. I got the expected result on my end.
Screenshot 2024-04-24 at 8 58 41 PM

**Review by nickolasram — APPROVED** [review]
Like everyone else, all the tests passed for me. I'll add an approval to this PR. 👍

**Comment by IsaacJrTypes** [comment]
I finally was able to update my repo since there needed to be test rewrites. I also removed a test since some of the components are still being developed. Removed SWC modules since we have decided to use TSC for testing transpilation. I know we agreed to place tests next to the component. The Issue I am running into is getting a proper setup where the files next to components get added to the code coverage report. Given the extensive research and setup, I will get back to it another time so I can move forward in my sprint.

**Pull request closed without merging**
