### PR TITLE
belindas-closet-nextjs_6_348_adding-security-research-file

### PR DESCRIPTION
**Pull request by Asfand00**
Resolves Issue #348 
This PR adds a .pdf file that contains the best app security practices from A01-A05 on OWASP for Belinda's closet. 

View file here: 
[Security-Research-1_A01-A05.pdf](https://github.com/SeattleColleges/belindas-closet-nextjs/files/15269694/Security-Research-1_A01-A05.pdf)

Any feedback or changes is appreciated. Is the format ok? or should I use markdown instead?

### CODE REVIEW

**Review by taylorpapke — CHANGES_REQUESTED** [review]
You can just link to the pdf (or google doc, notion, etc) from the issue. No PR/code review is necessary for this type of documentation. @brinkbrink Do devs have access to creating notion docs or do they need some type of access from you? Is there a specific folder they can use?

**Comment by brinkbrink** [comment]
> You can just link to the pdf (or google doc, notion, etc) from the issue. No PR/code review is necessary for this type of documentation. @brinkbrink Do devs have access to creating notion docs or do they need some type of access from you? Is there a specific folder they can use?

They shouldn't need special permissions but if anybody has trouble, just send me a DM on Slack. A few folks have been able to do so without any permission changes. I have created a "Developer Wiki" where docs should live. I'll go over that on Thursday but I can always move the doc if people don't see the dev wiki.

**Comment by Asfand00** [comment]
> You can just link to the pdf (or google doc, notion, etc) from the issue. No PR/code review is necessary for this type of documentation. @brinkbrink Do devs have access to creating notion docs or do they need some type of access from you? Is there a specific folder they can use?

@taylorpapke, I'm not sure what you mean by link to the pdf from the issue, do you mean just have a link to the pdf on the issue page #348 and approve it from there, no PR? would you guys be notified if I added the link there?

**Comment by taylorpapke** [comment]
@Asfand00 Yeah, it looks like you have the pdf included in issue #348 and I personally think that should be enough to complete your user story. I think we should discuss this more on Thursday but I don't think the research documents need to be reviewed and approved. The documents will just be used to help aid implementation in the next sprint so having it documented in an issue would be good (and a centralized place like notion would be ideal).

**Comment by Asfand00** [comment]
> @Asfand00 Yeah, it looks like you have the pdf included in issue #348 and I personally think that should be enough to complete your user story. I think we should discuss this more on Thursday but I don't think the research documents need to be reviewed and approved. The documents will just be used to help aid implementation in the next sprint so having it documented in an issue would be good (and a centralized place like notion would be ideal).

@taylorpapke I see so should I close this PR then? I checked on notion and it seemed my file was published on the developer wiki for people to view. I'm also doing the second half still of my user story so it's not done yet for A06-A10 issue #349

**Comment by taylorpapke** [comment]
> > @Asfand00 Yeah, it looks like you have the pdf included in issue #348 and I personally think that should be enough to complete your user story. I think we should discuss this more on Thursday but I don't think the research documents need to be reviewed and approved. The documents will just be used to help aid implementation in the next sprint so having it documented in an issue would be good (and a centralized place like notion would be ideal).
> 
> @taylorpapke I see so should I close this PR then? I checked on notion and it seemed my file was published on the developer wiki for people to view. I'm also doing the second half still of my user story so it's not done yet for A06-A10 issue #349

@Asfand00 Yes, you can close this PR. Thanks!

**Pull request closed without merging**
