### PR TITLE
belinda-nextjs-151-fix-ci-on-pull-request-01

### LINKED ISSUE #151: Bug: Fix CI on Pull Request
CI is not triggering properly for updates to pull requests. We never updated nextjs repos with our fix for the other repos. Here is what we did to fix this for the android repo:

Image

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #151 
Currently, CI is not triggering properly for updates to pull requests. We never updated NextJS repos with our fix for the other repos.
This will fix bug CI on pull request.
image

### CODE REVIEW

**Review by Exochos — DISMISSED** [review]
Looks good!

**Review by bcko — APPROVED** [review]
👍

**Review by taylorpapke — APPROVED** [review]
LGTM! Let's apply this same fix to nsc-events-nextjs repo ASAP!

**Comment by tinpham5614** [comment]
> LGTM! Let's apply this same fix to nsc-events-nextjs repo ASAP!

I will do it

**Pull request merged**
