### PR TITLE
Belindas-Closet-nextjs-8-452-mission-page-unit-test

### LINKED ISSUE #452: Unit Test: Mission Page Unit Test
- [ ] Resolves lack of a unit test for mission page rendering.

### PR DESCRIPTION
**Pull request by MaddasaHatter**
Resolves #452 
This unit test tests current function/rendering while leaving space to test new functions as they are added.
Screenshot 2024-06-10 224445

### CODE REVIEW

**Review by Seiyaroo — APPROVED** [review]
LGTM

**Comment by Diego-Cano** [comment]
Hello,

I checked the unit test you wrote for the Mission Page component. Nice work on setting up the initial test to render the mission page and check for the 'Our Mission' header. I like how you used the getByText function to check for the 'Our Mission' header. This makes sure the key element we're looking for is present in the DOM. The test seems great and leaves room for future functions, which is great planning. The way you've structured the test with a clear describe block for the 'MissionPage component' and a specific test block for rendering is very clean and easy to understand. This not only makes the test readable but also maintainable for future updates. It's also great to see that you've included a comment to add more assertions as needed, which shows foresight for expanding the test coverage.


I found a helpful link on the subject:
 [React.js Unit Testing: Best Practices and Tools with examples
](https://medium.com/@natnael.awel/react-js-unit-testing-best-practices-and-tools-5454a01326ea)

Screenshot 2024-06-11 at 5 11 53 PM

**Review by Diego-Cano — APPROVED** [review]
Great Job!

**Review by intisarosman1 — APPROVED** [review]
LGTM! The test runs successfully.
Screenshot 2024-06-12 005231

**Pull request merged**
