### PR TITLE
belinda-closet-nextjs_5_279_mission-page-with-route

### LINKED ISSUE #279: USER STORY: Mission Page
As a visitor, I will want to know the mission of this website through navbar.

Tasks:
- [x] Placeholder (blank) page for mission
- [x] Create link for navbar

Mission_page

### PR DESCRIPTION
**Pull request by JoyZhang2023**
Resolves #279
This pr is to create a placeholder page for mission and add route to Navbar.
image

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks good. @keiffer213

**Review by tinpham5614 — APPROVED** [review]
Thank you for creating this page.
Just one comment, we can edit lines of code instead of deleting and re-adding the entire contents of a file.

**Comment by nickolasram** [comment]
Good afternoon, @JoyZhang2023 . I have tested and can confirm everything works as expected (though my approval is redundant at this point.) Since you have 2 or more approving reviews you can squash and merge this branch into main 👍 Just click on the green button below and then confirm. Git will take a minute to check if everything is copacetic and then it'll commit your changes to the main branch. Don't forget to run a git pull on your local version of the main branch afterwards. 👌

**Review by keiffer213 — APPROVED** [review]
Looks good! The button works to reroute to the missions page!

**Pull request merged**
