### PR TITLE
Belindas-closet-nextjs-2-214-Signup-Page

### LINKED ISSUE #214: Sign up Page: Connect to backend API.
Relates to #222
Right now the sign up page is connected to a built-in next.js API and doesn't work correctly, it's a quick fix but since nest.js is needed to be utilized,  I guess it makes sense to make the sign up function send requests to nest.js. Nest.js sign up function requires an additional field "role" for a user, but it shouldn't be an issue because the main sign up page is made to sign up regular users, I didn't see in the project yet where the sign up page for admins belongs.

### PR DESCRIPTION
**Pull request by zmagar**
Resolves #214 
Changed sign-up page to send a POST request to the Nest.js backend. 
To test:
local nest.js server with MongoDB need to be working, if port is different from 3000, it needs to be changed in /belindas-closet-nextjs/app/auth/sign-up/page.tsx to the one your server is using. 
Go to signup page http://localhost:8080/auth/sign-up (again, check your ports), enter the required data and click the Sign Up button, if it is successful, you'll see the alert and the response from the API with the token like this:

Screenshot_20240215_112020a

Also there should be the new entry for the new user you signed up in the Nest database:

Screenshot_20240215_112250

### CODE REVIEW

**Comment by tinpham5614** [comment]
It works as expected according to the screenshot. However, the code is not up to date with the main branch. Please update it.
image

**Review by taylorpapke — APPROVED** [review]
This worked for me. I was able to sign up and a success alert was displayed. Upon checking my database, I saw that I had been added as a creator:
Screenshot 2024-02-16 at 2 06 03 AM

@zmagar I think you can convert this from a draft when you are ready. @Seiyaroo A couple things that came to mind while reviewing this are the following:
- For now, I am automatically signed up as a creator when I sign up. Will we want to change this behavior in the future to sign up new users as the user role and then have admin change their role to a creator or admin role?
- Users have no access to creator or admin pages, so what will be the action when a user with user role signs in? Currently, it is routing to a placeholder profile page but should we just route them back to the home page? It doesn't seem to make sense for the user role to have a profile page if they have no privileges or actions that they can make (yet). Belinda's Closet was a little different from nsc events in that aspect. Users only have the ability to view the app regardless of whether they are signed in/out. If they are signed in, they should at least have the option to sign out on the nav bar but obviously no access to creator or admin pages.

**Comment by tinpham5614** [comment]
The signup function works as expected.
My concern is will this PR with 19 files changed conflicts with the main branch.

**Comment by zmagar** [comment]
@tinpham5614 Yeah, I'll create a new pull request from the updated branch to make it cleaner

**Pull request closed without merging**
