### PR TITLE
belindas-closet-nextjs_6_330_qa-testing-components

### PR DESCRIPTION
**Pull request by kaimanasse15**
The code has no error but the test does after I run every time
Assignment #330

### CODE REVIEW

**Comment by taylorpapke** [comment]
Similarly to what happened on nsc events, I think we should wait until @IsaacJrTypes gets his PR merged. Once the testing framework is installed and set up properly, we can start writing our tests.

**Comment by nickolasram** [comment]
@kaimanasse15 Isaac's PR has been merged so it might be worth it to revisit this

**Comment by Diego-Cano** [comment]
For those of us newer to handling GitHub pull requests and managing dependencies, it might be helpful to review some resources on these topics. Here’s a guide from GitHub on [managing dependencies and security](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies), which provides insights into keeping our project secure and efficient. This is my first time taking a practicum class, so I have had to do some extra research to catch up with my classmates. I just wanted to share this link.

**Comment by Seiyaroo** [comment]
I worked with Kai on this briefly and his pull is having some issues but I think they center around the node modules packages being attempted to merge. We should make sure tonight in class that they are needed or not for merging. Would be a good lesson on Git stuff outside the normal Add, Commit, Push stuff we see. Will bring it up tonight with BC!

**Comment by taylorpapke** [comment]
@kaimanasse15 Closing this PR. I believe you were going to create a new PR for these tests.

**Pull request closed without merging**
