### PR TITLE
belindas-closet-nextjs_9_472_update-creator-page

### LINKED ISSUE #472: Chore: Add links and archive products button to Creator Page
On the Creator Page, Link the "All Products" button to all-products page and create an archive products button and link to the archived products page.

Currently how the Creator Page looks:
creator-page1

### PR DESCRIPTION
**Pull request by Asfand00**
Resolves #472 

This PR is for updating the creator page with a new button and link for the "archived products page" and adding a link to the "all products page".

This video link here demonstrates the changes made:
https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91708459/cb900da6-72a0-476d-89ea-bae0f1ee5540

also updated the jest test page for creator page because of failing checks.

to test this: `npm run dev` then route to /creator-page

### CODE REVIEW

**Review by intisarosman1 — APPROVED** [review]
The buttons redirect to the right pages, LGTM!
image

**Review by keiffer213 — APPROVED** [review]
Thank you for working on this and I appreciate that you updated the unit test as well!

**Comment by ParysUnangst** [comment]
Thank you for updating the unit test and creator page! Its great two have the separation between the current and archived products. 
creator page
GAME ON SIR!!!

**Review by ParysUnangst — COMMENTED** [review]
Well Done!

**Pull request merged**
