### PR TITLE
belindas-closet-nextjs_7_392_nav-bar-drop-down-menu

### LINKED ISSUE #392: Nav-Bar Drop down menu: Create My Account button and route to proper pages
As a developer, I will want to organize the nav-bar dropdown menu so that users can navigate to the correct page based on their roles.

Tasks:
- [x] Condense Profile and My account Link to one button (My Account)
- [x] Link My account depending on the user’s role signed in to route to proper page

oP_kxC-P5t95flnZPcDXOlGTTB-1o_iewtGBNran05-eqHKvgfc7QAJ2sft6TOqdI8UudR8PnxHLT_oKRa6V0gLVyBua1Py-x8YWgQvIlBqY_zqraA-ar5BJWGC4HwbLfnERWuydMuC0lmWlv_PkNuc

admin -> admin page
creator -> creator page
user -> profile page

Relates to #391

### PR DESCRIPTION
**Pull request by heosman**
Resolves #392 

This PR condenses the "Profile" and "My account" links in the nav bar into one link, "My Account". When an admin user clicks the "My Account" link, they are directed to the admin page. A creator who clicks this link will be directed to the creator page, and a user who clicks this link will be directed to the profile page.

image

Relates to #391

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Everything's working as expected. My account takes me to the proper page for the role I'm logged in as.

**Comment by kaimanasse15** [comment]
It looks good!
image

**Review by JesseCaddell — APPROVED** [review]
Your work looks great! I tested each role: user, creator and admin. All three have the new "My Account" button and it directs to the profile page.

**Comment by MuhammadNSC** [comment]
This works as expected. I logged in as an Admin and was directed to the admin page dashboard after clicking "My Profile". This will be great to allow each individual to access to there respective dashboard page.  
Screenshot 2024-05-22 at 6 05 26 PM

**Review by alasali1 — APPROVED** [review]
image
image
image

When I click to another page and then click on my profile, I go to the correct page for all three types of accounts. Seems to be working fine.

**Pull request merged**
