### PR TITLE
Feature ci pipeline 01

### PR DESCRIPTION
**Pull request by theGaryLarson**
CI: called on pull-request [opened, reopened] 

Implemented:
- code checkout
- node.js setup
- clean install with npm ci
- linting

CD:
- stubbed file for further development

### TODO CI Workflow:

Priority 1

- Code Compilation (tsc) In progress
- Install dependencies (complete)
- Linting (complete)
- Unit Testing (Jest) In progress

Priority 2

- Notification and Reporting (custom workflows as safeguards & alert to lead to provide further guidance)
- Security Checks (Dependabot)
- Code Coverage (Jest) in progress
- Integration Testing (Jest)
- Dependency Management (Dependabot)

Priority 3

- Build Artifacts
- Documentation Generation
- Accessibility Testing
- Performance Testing
- Quality Assurance Checks

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Awesome! I like the format of this and where it is going. This looks like a great model that we can use for both the web and mobile CI/CD pipelines in keeping more congruity all across the board!

**Review by brinkbrink — APPROVED** [review]
Thank you for your work on this, Gary! Looking good so far.

**Review by brandondombrowsky — APPROVED** [review]
LGTM

**Comment by brinkbrink** [comment]
I'm fine with bypassing to merge here, too.

**Comment by brinkbrink** [comment]
Resolves #3

**Pull request merged**
