### PR TITLE
Belinda_NextJS_Sprint_1_154_Added_Confirm_Password_Textfield

### PR DESCRIPTION
**Pull request by MuhammadNSC**
This is related to User Story #140 
I added confirm password textfield
Screenshot 2024-01-24 at 9 56 57 AM

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks good. Confirm password textfield is visible when I run the code.

**Review by tinpham5614 — DISMISSED** [review]
A conflict needs to be resolved.

**Comment by MuhammadNSC** [comment]
@tinpham5614 what is the conflict that I need to resolve for this issue

**Review by brinkbrink — APPROVED** [review]
The logic isn't quite working for client-side validation but your PR description only mentions the textfield and that is visible so I will approve, assuming that was your only intention here.

**Pull request merged**
