### PR TITLE
belinda-nextjs-04-235-add-profile-menu-to-navbar

### LINKED ISSUE #235: Profile Navbar: Link to admin/creator page
Add profile Icon and Redirect to admin page if user is admin or redirect to creator page if user is creator

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #235 
Previous PR (closed): #291
Related #234 #266 
This PR will add a profile menu to the navbar with the profile icon. This icon will appear once the user logged in.

Demo:

image

image

### CODE REVIEW

**Comment by Ali-7s** [comment]
LGTM.
Profile icon shows up when I log in and disappears when I log out.
image

**Comment by bennettsf** [comment]
Looks fine as long as this a feature strictly for 'user' roles! I tried this on an admin account and the icon didn't show, is that intended? 

I'm not sure the logout button is routing back to the home page like you intended it to with the [onClick function](https://github.com/SeattleColleges/belindas-closet-nextjs/pull/297/files#diff-08c2484ef2f4c7cb2894299963f13fa51ba92e33809236c1348343b8917b7102R28). When I logout from other pages (such as Donations/Mission), it keeps me there. 


I believe you can just remove `window.location.reload();` on L30 if your intended functionality is to redirect to '/'.

**Comment by tinpham5614** [comment]
Hi @bennettsf , just want to know something on your side:
- Do you have the backend run when logging in?
- Is there an admin account in your local MongoDB?

This is on my side when I logging with an admin account.

[Screencast from 2024-04-19 18-07-05.webm](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/72054441/7e7d1f2f-667d-452f-bdac-025f8d4c97e8)

Logging out will redirect users to the homepage and restrict non-access users from other pages, such as the add product page.

**Comment by bennettsf** [comment]
> Hi @bennettsf , just want to know something on your side:
> 
> * Do you have the backend run when logging in?
> * Is there an admin account in your local MongoDB?
> 
> This is on my side when I logging with an admin account.
> 
>  Screencast.from.2024-04-19.18-07-05.webm 
> Logging out will redirect users to the homepage and restrict non-access users from other pages, such as the add product page.

Works fine with Admin now (must have been my mistake.) However, I still can't get the page redirected to homepage when I press the Logout Button. Maybe we can get a test from someone else? 

I have the backend running and admin/users in my mongoDB

**Comment by tinpham5614** [comment]
@bennettsf Redirecting to the homepage upon logout was the intended behavior, but if you have any suggestions, I would be happy to consider them.

**Review by taylorpapke — APPROVED** [review]
Looks great! Very professional looking!
Screenshot 2024-04-22 at 2 29 25 PM
Screenshot 2024-04-22 at 2 32 52 PM

@bennettsf @tinpham5614 I believe this was from a previous sprint and was only for the UI appearance and not the functionality. I will go over this design and functionality and add new requirements for the next sprint so we can merge this as is.

**Review by bcko — APPROVED** [review]
Great job Tin!

**Pull request merged**
