### PR TITLE
Belinda_NextJS_Sprint_3_244_Transition_forget_password_page_to _MUI

### PR DESCRIPTION
**Pull request by krayzieeddi**
I have transitioned the forget-password page into the MUI CSS framework. 

NOTE: the form tag is still using the old CSS but cannot seem to have MUI syntax within the form tag. Let me know if you would like to me to transition the form tag into the new syntax via custom function method using MUI syntax.

### CODE REVIEW

**Comment by tinpham5614** [comment]
Thank you for making this change.
I implemented the sign-in page using Box with the component as a form. (similar to the NSC app)

image

**Comment by tinpham5614** [comment]
Currently the web appearance as the screenshot:
image

We may need to add more styling to make it visible.

**Review by taylorpapke — APPROVED** [review]
As @tinpham5614 mentions above, some styling is still required to make the text and fields visible. I will approve now with the expectation that this is updated prior to merging since this now a live site.

**Review by brinkbrink — CHANGES_REQUESTED** [review]
Please make the changes requested above. I am only adding this review so that we can enable auto-merge. When changes have been made, the next reviewer can dismiss this review as stale.

**Comment by krayzieeddi** [comment]
I have added more styling for more clarity and have updated the font to be more inline with the rest of the website. Let me know if there is anything else or something wrong

**Review by heosman — APPROVED** [review]
The text and fields are visible now, which is great. I'm not sure if the font of "Forgot Password" being different was intentional, but it seems to be inconsistent with the rest of the app.

**Comment by tinpham5614** [comment]
To maintain consistency across pages, you can use the sign-in page as a reference.
Current appearance:

image

Expecting something like this:

image

**Comment by krayzieeddi** [comment]
I have adjusted the forgot password page's style to look like the screenshot Tin has provided me.

**Review by tinpham5614 — APPROVED** [review]
LGTM

**Pull request merged**
