### PR TITLE
belindas-closet-nextjs_4_194_standardize_wrapper

### PR DESCRIPTION
**Pull request by nickolasram**
1.  I created a custom Box component to use as the center div wrapper on every page. Now it should be easier to change the general layout of the site going forward.
Code:
customBox
Example (The dark grey square in the center):
signinfrog

2. I wrapped every page in the new WrapperDiv component
Example code:
wrapper example

3. This is a little extra thing I did but I also brought the frog closer to (and slightly overlapping) the forms on the sign up and sign in page as you can see in the picture above as well as here:
signupfrog

### CODE REVIEW

**Review by Exochos — CHANGES_REQUESTED** [review]
image

So if you wrap the {children} in the layout.tsx you don't need to put it on each of the pages.
image

**Comment by nickolasram** [comment]
@Exochos recommended changes have been implemented

**Review by Exochos — APPROVED** [review]

**Comment by Exochos** [comment]
Fantastic work! 

> @Exochos recommended changes have been implemented

Thank you!

**Review by heosman — CHANGES_REQUESTED** [review]
Great job on making the pages appear more consistent, and fixing the frog on the Sign Up and Sign In page. There is now an issue with the buttons on the product cards on the product pages that should be addressed.

Screenshot 2024-03-19 183256

**Comment by nickolasram** [comment]
@heosman That should look better now

**Review by heosman — APPROVED** [review]

**Pull request merged**
