### PR TITLE
belindas-closet-nextjs_5_309_TutorialSetupMongoDBD3

### PR DESCRIPTION
**Pull request by el-riber**
As a developer I am working on creating a document with the aim of showing how to set up a library Dj3.js on MongoDB

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks great! This will help with setting this up if we decide to go this route. Is D3.js what you are recommending after doing your research? @brinkbrink @Seiyaroo

**Comment by brinkbrink** [comment]
I am interested in seeing your research on this subject. We can approve this but I would like to know more context. Can you also copy this over to Notion along with any other research you would like to share with the team on this subject?

**Review by Asfand00 — COMMENTED** [review]
Looks pretty good, some suggestions I would make is to add spaces between each step and organize the coding parts for better readability, it looks a bit hard to read how it is now.
An Example of this (In notepad++):
belinda-closet-d3-documentation

**Comment by miqo1385** [comment]
I will install mongoDB this week in my end. I hope this help me getting all set.

**Comment by tinpham5614** [comment]
If we need this research content in markdown file, I have a few comments:
- You can use VS Code (with Markdown Preview Enhanced extension) to edit and preview the markdown content.
- Highlight the title and steps for easy navigation. 
- Use triple backticks ``` start and end of the code portion to make them as code format.

Below is my edited version, you can use it for reference.
Let me know if you have questions.

image

**Review by nickolasram — APPROVED** [review]
I think it meets the requirements so I'll approve this for now, but I think others have given some great feedback on some changes that can be implemented.

**Comment by IsaacJrTypes** [comment]
Overall, the research looks good. If we keep the research document on github, adding markup will benefit everyone. I was wondering if you were able to provide a video or picture of your steps in action. Besides that, it would be helpful to add links to MongoDB setup guides for easy access.

**Comment by Diego-Cano** [comment]
This tutorial on integrating D3.js with MongoDB seems helpful for visualizing our project's data effectively. I found a couple of resources that might assist us further. For a straightforward guide on setting up MongoDB, this tutorial from MongoDB's documentation is clear and useful: (https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-windows/). It walks through the installation process step-by-step, which could be very handy.

Additionally, if we need a quick reference on how MongoDB can be used effectively in various applications, this beginner-friendly guide from freeCodeCamp breaks down the basics and provides simple, practical examples: (https://www.freecodecamp.org/news/how-to-start-using-mongodb/). This could be a great resource to share with the team, ensuring everyone understands how to interact with our data.

**Review by Seiyaroo — APPROVED** [review]
Overall this is really awesome to have. I think adding in the stuff in the future (or before merging if you want) to make it look prettier or aptly formatted like Tin provided could work. 

@taylorpapke I think D3.JS still sits pretty high if not #1 for JS visualization tools. It's also updated as recent as 3 days ago meaning we don't lose it being current and useful. I think because it also has a decent amount of documentation I'd personally go with it. Plotly could work but its primarily a Python library and I am not sure how well if any docs there are for a JS plotly?

**Review by taylorpapke — CHANGES_REQUESTED** [review]
Requesting changes to make sure this doesn't get merged in. @brinkbrink We want to copy these instructions over to notion? @el-riber have you done this already or are you able to do this?

**Comment by brinkbrink** [comment]
> Requesting changes to make sure this doesn't get merged in. @brinkbrink We want to copy these instructions over to notion? @el-riber have you done this already or are you able to do this?

Yes, please!

**Comment by taylorpapke** [comment]
Closing this PR. I exported the included documentation as a PDF and copied to notion under data in developer wiki.

**Pull request closed without merging**
