### PR TITLE
belinda-nextjs-chore-395-add-dark/light-mode

### LINKED ISSUE #395: Chore: Add dark/light mode
As a developer, I want to implement a dark/light mode (contrast polarity) on the web, allowing users to choose their preferred mode.

Here is the demo:

https://github.com/SeattleColleges/belindas-closet-nextjs/assets/72054441/655b8811-5be1-42a2-8b2f-9a7613958356

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #395 

This PR will add dark and light modes (contrast polarity) to the front end, allowing users to choose their preferred mode.
Also, I revised the pages by removing inline styling for consistent formatting.

**_Note: There appear to be numerous file changes, which I removed inline styling and formatting. The initial commit needs your feedback/review._**

I've included the tutorial for reference, which uses next-themes to implement this feature. However, with our tech stack of Next.js and Material UI, I had to make adjustments to get it to work.

Reference: 
[https://stackoverflow.com/questions/78170462/switching-between-system-dark-and-light-mode](https://stackoverflow.com/questions/78170462/switching-between-system-dark-and-light-mode) (similar to current approach)

[https://www.davegray.codes/posts/light-dark-mode-nextjs-app-router-tailwind](https://www.davegray.codes/posts/light-dark-mode-nextjs-app-router-tailwind)

Demo: 

https://github.com/SeattleColleges/belindas-closet-nextjs/assets/72054441/58039b67-e3c5-4a5a-a08b-03ed681b3705

### CODE REVIEW

**Comment by tinpham5614** [comment]
### Update results
Light Mode:
image

Dark Mode:
image

**Review by heosman — APPROVED** [review]
Looks great! I am able to switch between light mode and dark mode by clicking the theme button.

image
image

**Review by keiffer213 — APPROVED** [review]
This looks great! I was able to toggle the dark/light theme of the website on different pages with no issues!

https://github.com/SeattleColleges/belindas-closet-nextjs/assets/54779894/c8798f0e-b968-4cdc-839f-67484b3f58a5

**Review by IsaacJrTypes — APPROVED** [review]
Thank you for adding the cool new dark mode. The links were also very helpful in providing insight into your implementation approach.

**Comment by MaddasaHatter** [comment]
Looks good to me
https://github.com/SeattleColleges/belindas-closet-nextjs/assets/52189566/7c7d4aa2-93bd-43be-8e67-87ec64d69461

**Pull request merged**
