### PR TITLE
belindas-closet-nextjs_5_278_add-product-button

### PR DESCRIPTION
**Pull request by nwm516**
Resolves <issue #278 >

- Link "Add Product" button to correct page

https://github.com/SeattleColleges/belindas-closet-nextjs/assets/36825393/eb464b22-813c-4a0f-935d-15b5e1bbfedf

### CODE REVIEW

**Comment by nickolasram** [comment]
I haven't gotten around to testing the functionality of your update yet, but I have some guidance on how we structure user stories and issues and pull requests. I know this project is a lot to jump into and how it all works isn't necessarily easy to get at first. So when it comes to the miro board ... 
Screenshot 2024-04-17 225259
...the note I've circled above in red is going to be a User Story for this sprint. I see that you've made user story #278 . That's all good.  But then you have the other sticky notes I've circled in green. Each of those should be their own separate issue here on Github (or you can group them together if the tasks on the sticky notes are kinda small.) As you can see in this screenshot...

Screenshot 2024-04-17 225729

I have my "User Story: Add Product Page" and then I've made two issues that I relate to the User story by referencing the user story in the issues ... 

Screenshot 2024-04-17 231253

...and referencing the issues as tasks in my user story

Screenshot 2024-04-17 231423

I would do this even if I only have one issue attached to the user story.

I know this is a lot all at once so feel free to ask any questions.

What do I suggest you do? First, create an issue for each of the sticky notes I circled in green above (in the future, keep in mind that you can lump small tasks together into one issue.) Then, connect to your issue(s) to your user story by referencing them in each other's description. Then, instead of referencing the number of your user story as you did above where you wrote "Resolves <issue #278 >",  reference whatever number the issue pertaining to the add product button ends up being.

**Review by taylorpapke — APPROVED** [review]
I was routed to the add product page when I clicked the add product button on the admin page.

**Review by cshimm — APPROVED** [review]
Worked for me. I was routed to the add-product-page after clicking Add Product from the admin page.

**Review by keiffer213 — APPROVED** [review]
Works great for me! I was re-routed to the add-product page after clicking the button. 

It may not matter, but I noticed the comments for the other buttons on line 17 & 22 is link to "add-product-page" instead of  "All products" page and "edit user roles" page respectively

image

**Comment by nickolasram** [comment]
Hello, @keiffer213 . Since you have 2 or more approving reviews you can squash and merge this branch into main 👍  Just click on the green button below and then confirm.  Git will take a minute to check if everything is copacetic and then it'll commit your changes to the main branch. Don't forget to run a git pull on your local version of the main branch afterwards. 👌

**Review by BradleyCharles — COMMENTED** [review]
Add product button seems to be functioning

admin1
admin2

**Pull request merged**
