### PR TITLE
Belinda_NextJS_Sprint_3_235_Add_Profile_To_Navbar

### PR DESCRIPTION
**Pull request by MuhammadNSC**
I added a profile to the navbar that has a dropdown showing profile logout and my account 

Screenshot 2024-02-29 at 7 16 32 PM

### CODE REVIEW

**Comment by MuhammadNSC** [comment]
@tinpham5614  @taylorpapke can you please this draft request to see if its good. I added a ProfileDropDownMenu.tsx to the components

**Comment by tinpham5614** [comment]
I don't see your changes. Can you create a new local branch instead of working on the previous PR?
image

**Comment by MuhammadNSC** [comment]
Hey Tin. GPG was trying to sign but was not working so I just ignored the sign. I push back the same branch and you should see the changes now. Its simple change just a profile dropdown but without the icon and a profile, my account and logout link

**Comment by tinpham5614** [comment]
@MuhammadNSC You might need to update the latest code. 
I think the profile menu should be displayed after the user signs in and disappears after logging out.

**Comment by tinpham5614** [comment]
I can still see the profile menu without logging in.
If you make this branch into a PR, I'm concerned about too many conflicts.

image

**Comment by MuhammadNSC** [comment]
Screenshot 2024-02-29 at 7 16 32 PM
This is how it should look like. Did you run this branch feature-235-add-profile-navbar-3

**Comment by tinpham5614** [comment]
Here is appearance as a creator:

image

**Pull request closed without merging**
