### PR TITLE
belindas-closet-nextjs_5_288-327_EditUserRoleDialog-Component-Alert

### PR DESCRIPTION
**Pull request by Asfand00**
Resolves Issue #288 and Issue #327 
This PR is for pushing new additions to the EditUserRoleDialog.tsx Component onto this branch. 
Changes: Added new Alert and Snackbar to message users that the role has been changed on the edit-user-role-page. 

Side Note: Currently having Issues with my commits not being verified need to resolve. any help is appreciated. 

The issue #288 states that the alert message should be in a specific format, for now it simply says that on success "User role updated successfully". (edited user story #286 to include this)

(update)
I have Tested the changes and they are successful on my end and works as intended. 

I first made two users on MongoDB using Postman and I have it connected to the Belinda's closet nest.js .env file: 
mongodb-users

you can see them listed here on the edit-user-role-page:
edit-user-role-page

When I go to change the User role for the Asfand Tanwer account, logged in as the John Doe account, I get a success alert on the bottom left:
edit-user-role-page-change
afterwards you can refresh the page and you will see the user roles changed. 

Also when I am logged in as Asfand Tanwer as creator and try to change the John Doe role which is admin, I get the error message on the bottom left:
edit-user-role-page-error

### CODE REVIEW

**Review by alasali1 — COMMENTED** [review]
When trying to test this by logging into two different accounts simultaneously I was unable to see the snackbar message when changing the user role for the other account, also when changing the role for the admin account itself.

image

**Review by taylorpapke — APPROVED** [review]
Everything's working properly and I'm seeing the correct toast messages.
Logged in as admin:
Screenshot 2024-04-30 at 2 42 12 AM
Logged in as creator:
Screenshot 2024-04-30 at 2 43 02 AM

**Review by nickolasram — APPROVED** [review]
Everything looks great! You should be able to merge this into main now

**Comment by nickolasram** [comment]
I just noticed you can't merge because your commits aren't signed. [Here is a tutorial on how to sign your commits.](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

**Comment by Asfand00** [comment]
> @Asfand00 I just noticed you can't merge because your commits aren't signed. [Here is a tutorial on how to sign your commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for the next sprint.

Yeah I'm having issues trying to sign my commits it won't work, I have my GPG key setup but it's not detecting it for some reason

**Pull request merged**
