### PR TITLE
belindas-closet-nextjs_1_179_product-page

### LINKED ISSUE #179: Edit Product Page: Create a product page
relates to: #139 

As a developer, I want to have the product page that displays all the products from a specific product category.

### PR DESCRIPTION
**Pull request by TroyFPV48**
Resolves #179 
Added product category pages, added filter section, and captured all products from the back-end using "localhost:3000/api/products".

### CODE REVIEW

**Review by Exochos — APPROVED** [review]
Code looks great and everything works on my end

**Review by taylorpapke — CHANGES_REQUESTED** [review]
This filtering feature is really awesome! However, this is not a requirement from the client and so we will have to remove this feature. The design choice that we are going for is very simplistic with products unsorted within their categories. Very impressive work but we have to avoid feature creep as this project is on a strict timeline.

**Comment by TroyFPV48** [comment]
> This filtering feature is really awesome! However, this is not a requirement from the client and so we will have to remove this feature. The design choice that we are going for is very simplistic with products unsorted within their categories. Very impressive work but we have to avoid feature creep as this project is on a strict timeline.

I have removed the filter section. Please review it again.

**Review by taylorpapke — APPROVED** [review]

**Comment by taylorpapke** [comment]
Looks great! Thanks for making the changes.

**Pull request merged**
