### PR TITLE
Belinda_NextJS_Sprint_1_166_Password_Toggle

### PR DESCRIPTION
**Pull request by MuhammadNSC**
This relates to User Story #140. 
I added a Show/Hide Password Input Field.
Screenshot 2024-02-01 at 1 29 51 PM
Screenshot 2024-02-01 at 1 30 08 PM

### CODE REVIEW

**Comment by tinpham5614** [comment]
It works on my end.
Follow-up question: Should we create icons in each field, similar to the NSC page?

https://github.com/SeattleColleges/belindas-closet-nextjs/assets/72054441/4a025f78-1c04-4d32-af1a-2e56d621bf4d

**Comment by MuhammadNSC** [comment]
@tinpham5614 I saw how NSC did it and I tried implementing the same concept. I was not sure if NSC imported the lock/unlock icon.

**Review by taylorpapke — CHANGES_REQUESTED** [review]
I believe they have implemented the eye toggle on nsc events and I think we should do the same here. This may require material ui but now is as good of a time as any to start implementing this styling and carrying over what @NahomAlemu has been working on over there.

**Comment by taylorpapke** [comment]
@MuhammadNSC What is the status of this PR? Are you still working on this or can someone that needs a task help out?

**Comment by MuhammadNSC** [comment]
@taylorpapke I have moved on to other PR. Yes if anyone need a task they can help out

**Comment by NahomAlemu** [comment]
@MuhammadNSC Sorry for the late reply. We have used MUI but, I think we may achieve a similar look and functionality using custom CSS. Let's work on this together and get this PR merged. DMing you on Slack...

**Comment by cshimm** [comment]
I integrated the visibility icon from the NSC events project. Is this what were looking for? If so I can push my commit to the branch.
image
image

**Comment by NahomAlemu** [comment]
@taylorpapke so you suggesting refactoring to material UI? If so, will that be only for this page or are we planning to refactor the styling to MUI in  Belinda's project?

**Comment by Exochos** [comment]
> @taylorpapke so you suggesting refactoring to material UI? If so, will that be only for this page or are we planning to refactor the styling to MUI in Belinda's project?

I believe the eventual plan is to refactor Belinda's to also use MUI but I would also like clarification @taylorpapke

**Comment by taylorpapke** [comment]
> > @taylorpapke so you suggesting refactoring to material UI? If so, will that be only for this page or are we planning to refactor the styling to MUI in Belinda's project?
> 
> I believe the eventual plan is to refactor Belinda's to also use MUI but I would also like clarification @taylorpapke

Yes, this is correct. We will be refactoring all of Belinda's to use MUI in the same fashion as nsc events. @nickolasram has claimed this task on the sprint 2 planning board. I will also add that while nsc events and Belinda's closet have diverged in a lot of ways, the original intent was to increase production rate by creating these 2 apps side by side and reusing features where applicable. The only thing that differentiated the 2 in the beginning was that 1 dealt with products and the other with events. I would hope that we could retain extremely similar code cross-product when it comes to pages that are nearly identical to improve the ability to reference a working example.

**Comment by NahomAlemu** [comment]
@taylorpapke sounds good. Thanks for the explanation. If that is the case, @cshimm got it. Also, he expressed an interest in helping with the refactoring effort and I think can collaborate with @nickolasram

**Comment by brinkbrink** [comment]
With all this being said, can we close this PR assuming a PR for this user story will be opened elsewhere using MUI? I'm closing to avoid confusion but let me know if that's not what we want to do.

**Comment by taylorpapke** [comment]
I think @cshimm had changes to push to this PR to complete it. Is that correct?

**Review by tinpham5614 — APPROVED** [review]
Looks good to me.
Follow-up question: Do we want both fields (password and confirm password) to display at once or separate them?

**Comment by taylorpapke** [comment]
> Looks good to me. Follow-up question: Do we want both fields (password and confirm password) to display at once or separate them?

I think separating them would be nice but we can come back for it later in another PR.

**Review by taylorpapke — APPROVED** [review]

**Pull request merged**
