### PR TITLE
< Belindas-closet-nextjs> _ <8 > _ < 444> _ < archive products - fixed>

### PR DESCRIPTION
**Pull request by el-riber**
This is a pull request!

Please use the following format for the title:
< Belindas-closet-nextjs> _ <8 > _ < 444> _ <  archive products - fixed>

Please fill out this description with the following:
Resolves <issue #> 444
As a developer I created the page to archive products.
I made all the codes necessary to run the program. This includes the page, the api to make the connection between the images and the page.

I made all the necessary changes for the code to run in Typescript.

ps: I tried to make the pull request through VSC but today it's very slow, so I added the files here directly, I hope it works, if it doesn't work I'll try through VSC again

Screenshot 2024-06-09 at 1 47 44 PM
Screenshot 2024-06-09 at 12 52 08 PM
Screenshot 2024-06-09 at 2 24 40 PM

### CODE REVIEW

**Review by taylorpapke — CHANGES_REQUESTED** [review]
These files need to be under the app folder in a page folder like the other pages:
Screenshot 2024-06-09 at 2 59 35 PM

**Comment by el-riber** [comment]
But it is just like that, the problem is with the pull request. I will try to fix it

Screenshot 2024-06-09 at 4 41 38 PM
Screenshot 2024-06-09 at 4 42 24 PM

**Comment by MaddasaHatter** [comment]
Not to dog pile and I don't know if you have had a chance to update this yet but I don't see the folder for the page when I checkout your branch either.

**Comment by el-riber** [comment]
api test screen..
page test screen

a1
a2

**Comment by taylorpapke** [comment]
This PR doesn't include the package.json and the conflicts that arise are too complex to resolve. 

I think an easy fix would be to create a new branch from main and copy over the single page.tsx. A good example of how this should look is on the nsc-events website: https://github.com/SeattleColleges/nsc-events-nextjs/blob/main/app/archived-events/page.tsx.

**Comment by kaimanasse15** [comment]
It looks great but I don't see any images?
image

**Comment by el-riber** [comment]
> It looks great but I don't see any images? image
you can not see any image because you have to add images to the public/image file so the api will show the images. I hope so. I you see my files is not included the image.

**Pull request closed without merging**
