### PR TITLE
Belindas-closet-nextjs_6_369_enable-auto-assign-issues

### LINKED ISSUE #369: Chore: Enable NextJS Auto-Assign Issues Workflow
This issue is for implementing a .github/workflows yaml file that will auto-assign an issue to whomever creates the issue.

GitHub Marketplace action: https://github.com/marketplace/actions/auto-assign-issue

Documentation used: https://andrewlock.net/auto-assigning-issues-using-a-github-action/

Steps:
- Created personal access token for seattlecolleges and added to organization secrets.
- Created yaml file in .github/workflows folder that utilizes the secret to auto-self-assign creator of the issue.

### PR DESCRIPTION
**Pull request by taylorpapke**
Resolves #369 

Once merged, this should auto-assign developers to the issues they create for this repo.

### CODE REVIEW

**Comment by MaddasaHatter** [comment]
Looks good to me. Thanks for the work on this issue.

**Review by heosman — APPROVED** [review]

**Comment by kaimanasse15** [comment]
Looks good to me. Thanks, Taylor
image

**Review by keiffer213 — APPROVED** [review]
Thanks for doing this! It will really help for future issues!

**Comment by MuhammadNSC** [comment]
This will be a great feature enhancement added to the project. Looks great
Screenshot 2024-05-15 at 4 23 07 PM

**Comment by Diego-Cano** [comment]
Great job! This feature is very convenient! I found an interesting link too: https://github.com/andrewlock/auto-assign-issues Screenshot 2024-05-16 at 6 43 17 PM

**Review by Asfand00 — APPROVED** [review]
Looks good @taylorpapke, I'll just help approve this along.
auto-assign-issues

**Review by intisarosman1 — APPROVED** [review]
This will be a useful feature here on out! Looks good

**Review by ParysUnangst — COMMENTED** [review]
Thank you Taylor!

**Pull request merged**
