### PR TITLE
belindas-closet-nextjs_Sprint7_issue#403_UnitTest:Creatorpage

### PR DESCRIPTION
**Pull request by alasali1**
Resolves issue #403 
This Unit test tests the creator page, and makes sure the filler text renders properly, and that the hyperlink buttons operate correctly.

### CODE REVIEW

**Comment by MaddasaHatter** [comment]
The test passes but I get a console error any time I run the test. All the Belinda's test have the same name so I temporarily changes the name of this test so I could run just it to make sure. To fix the navigation-related error in your test, you should mock the Next.js router to prevent actual navigation actions during the test.
Screenshot 2024-06-04 235232

**Review by taylorpapke — APPROVED** [review]
Passes for me but I am also getting an error:
Screenshot 2024-06-05 at 12 07 10 AM

**Review by keiffer213 — APPROVED** [review]
This looks great! I am also getting the error, but It seems the error is somewhere else in the code. I'll put it on the backlog to fix in a future sprint!

image

**Review by tinpham5614 — APPROVED** [review]
Looks good to me!

**Pull request merged**
