### PR TITLE
Unit Test for the Donation Page

### PR DESCRIPTION
**Pull request by kaimanasse15**
This is the Unit Test for the Donation Page
Issue: #367

### CODE REVIEW

**Review by alasali1 — APPROVED** [review]
The written code makes sense to me and when I run jest I get a passing result, which is in line with what I see on the donation page.

image

**Review by taylorpapke — APPROVED** [review]
Works for me:
Screenshot 2024-05-18 at 12 52 45 PM

**Review by intisarosman1 — APPROVED** [review]
The test passes, looks good to me!
Screenshot 2024-05-20 233709

**Review by heosman — APPROVED** [review]
The test passed on my end.

image

**Comment by MuhammadNSC** [comment]
All tests passed on my end. I think understanding the function of the DonationInfo component this is a crucial test for ensuring that the component's basic structure is rendered as expected.
Screenshot 2024-05-21 at 2 06 44 PM

**Comment by nickolasram** [comment]
Works for me too. Great job! You should be able to merge this now

**Pull request merged**
