### PR TITLE
belinda-nextjs-6-353-add-auto-update-new-code

### LINKED ISSUE #353: CI/CD Deployment: Update CI to get new code
Implementing CD in our CI/CD workflows, should allow for merged code to be immediately deployed to our live website.

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #353 
Related https://github.com/SeattleColleges/belindas-closet/issues/73

This PR will allow for merged code to be immediately deployed to our live website.

Following ssh.yml in the nsc-nestjs, I've changed a couple of things:
1. Added `node-version: [18.x, 20.x]` to allow system using various node version
2. Changed IP address from `deployuser@54.186.121.210` to `deployuser@44.238.195.106`
_Note: Not sure where the IP address **54.186.121.210** comes from, so I tested with **44.238.195.106** as our IP address and it works_ 

#### 2. Click the Action tab as the screenshot
image
#### 3. Select the Continuous Deployment as the screenshot
image
#### 4. Click "Run workflow" to trigger the event on the right screen as the screenshot.
image

**Successful pull and restart pm2**
_Note: Maybe we need the next PRs to see changes in the online web version._
image

image

image

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks good. An ssh.yml has been created for deployment purposes.

**Review by nickolasram — APPROVED** [review]
Everything seems to be working. Great job!

**Comment by Diego-Cano** [comment]
Good job on setting up the continuous deployment! Switching the IP address to 44.238.195.106 and adding the Node versions to support 18.x and 20.x . It will definitely enhance our deployment flexibility. I appreciate the clarity in your testing steps and the screenshots; they really help in visualizing the workflow process.

**Review by TuongPhamM — APPROVED** [review]
Looks good to me.

**Pull request merged**
