### PR TITLE
belindas-closet-nextjs_10_510_admin-creator-page-buttons

### LINKED ISSUE #510: Bug: Fix Admin/Creator Page Buttons
As a developer, I will want to fix the appearance of the buttons on the Admin and Creator pages in light mode.

Screenshot 2024-07-20 214117
image

### PR DESCRIPTION
**Pull request by intisarosman1**
Resolves #510

This PR fixes the appearance of the buttons on the Admin and Creator pages, especially in light mode.

Before:
Screenshot 2024-07-20 214117

After:
Screenshot 2024-07-20 232803

### CODE REVIEW

**Review by heosman — APPROVED** [review]
Looks good!

image
image

**Review by Ali-7s — APPROVED** [review]
LGTM!
image
image

**Comment by keiffer213** [comment]
This looks great! unfortunately, I just saw that another PR just got merged which makes the admin and creator page implement role-based authorization, I'm not quite sure if it will be difficult or confusing to try to resolve the conflicts. Any suggestions?

**Comment by intisarosman1** [comment]
> This looks great! unfortunately, I just saw that another PR just got merged which makes the admin and creator page implement role-based authorization, I'm not quite sure if it will be difficult or confusing to try to resolve the conflicts. Any suggestions?

The merge conflict has been resolved now!

**Pull request merged**
