### PR TITLE
belindas-closet-nextjs_6_356_data-visualization-mongodb

### PR DESCRIPTION
**Pull request by el-riber**
As a developer/researcher I did the research for implementation of providing visualization from MongoDB database.

### CODE REVIEW

**Review by keiffer213 — APPROVED** [review]
The documentation for data visualization looks great! It is very detailed with instructions, processes, examples, and event bibliographies.

**Comment by keiffer213** [comment]
@brinkbrink Should we move this data visualization research over to notion?

**Comment by brinkbrink** [comment]
> @brinkbrink Should we move this data visualization research over to notion?

@el-riber @keiffer213  Yes, please!

**Review by BradleyCharles — APPROVED** [review]
Very clear instructions with a lot of visual aids!

**Review by alasali1 — APPROVED** [review]
This is very detailed and concise, focusing on one selected solution. I would have beneitted from using this as an example for data visualization research for android.

**Review by taylorpapke — CHANGES_REQUESTED** [review]
Let's copy this documentation somewhere it can be viewable online (example: google doc, notion, etc) and link it from the issue. Also, to avoid accidentally merging into our codebase, I don't think we need to do PR/code review for this type of documentation. @brinkbrink Are devs able to create notion docs or do they need access from you?

**Pull request closed without merging**
