### PR TITLE
belindas-closet-nextjs_1_183_add-nav-menu-for-product-categories

### LINKED ISSUE #183: Navigation Bar: Add nav menu for product categories
As a student, I will want to be able to navigate the website to find clothes from different categories.

- Add a “products” dropdown menu for product categories
- Have the categories listed in the dropdown with no action on click

Related to #142

### PR DESCRIPTION
**Pull request by heosman**
Resolves #183 

This PR adds a drop-down menu for the product categories. There is currently no action on click.

Screenshot 2024-01-28 202649

Linked to #142

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks good and is working on my end. I'm able to open and close the dropdown.

**Comment by tinpham5614** [comment]
Looks good to me. I just have a question: Should we implement this using Material UI now?

**Comment by brinkbrink** [comment]
@tinpham5614 That is a good question. Is this something that could be covered by the convert to Material UI user story?

**Review by brinkbrink — APPROVED** [review]
I will leave the Material UI to that conversion user story for now. Since we will be working on this product for another sprint I am comfortable merging this for now.

**Pull request merged**
